### ISSUE TITLE
runtime configurable reasons

### ISSUE THREAD

**Issue by jesopo** [Libera-Chat/maskwatch-bot#3]
once a solution to #2 lands, it would be nice if reasons were configured at runtime, via commands, rather than in `config.yaml`.

**Comment by examknow** [comment]
I wonder if there's a nice [library](https://github.com/examknow/ircconfig) to make this easier...

**Comment by jesopo** [comment]
I'd prefer to keep additional runtime options in SQL like the masks currently are
